[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "tencentcloud-sdk-python-im"
authors = [{name = "Pinclr", email = "coding@pinclr.com"}]
dynamic = ["version", "description"]
